In [38]:
import torch
import numpy as np

def print_tensor(name: str, r: torch.tensor):
  print('----------------------------------------------')
  print(f"{name}.size(): {r.size()}")
  print(f"{name}.dtype: {r.dtype}")
  print(f"{name}: {r}")
  print('----------------------------------------------')

# 0階のテンソル
r0 = torch.tensor(1.0).float()
print_tensor('r0', r0)

# 1階のテンソル
r1_np = np.array([1, 2, 3, 4, 5])
r1 = torch.tensor(r1_np).float()
print_tensor('r1', r1)

# 2階のテンソル
r2_np = np.array([[1, 2, 3], [11, 12, 13]])
r2 = torch.tensor(r2_np).float()
print_tensor('r2', r2)

# 3階のテンソル
r3_np = np.array([[[1, 2, 3], [11, 12, 13]], [[101, 102, 103], [111, 112, 113]]])
r3 = torch.tensor(r3_np).float()
print_tensor('r3', r3)

# テンソルの2階化
r3_to2 = r3.view(3, -1)
print_tensor('r3_to2', r3_to2)

# テンソルの2階化②
r3_to2_No2 = r3.view(2, 6)
print_tensor('r3_to2_No2', r3_to2_No2)
r3_to2_No3 = r3.view(2, -1)
print_tensor('r3_to2_No3', r3_to2_No3)

# テンソルの1階化
r3_to1 = r3.view(-1)
print_tensor('r3_to1', r3_to1)

# 4階のテンソル
r4 = torch.randn((2, 3, 2, 3))
print_tensor('r4', r4)

# 5階のテンソル
r5 = torch.ones((2, 1, 2, 1, 3))
print_tensor('r5', r5)


----------------------------------------------
r0.size(): torch.Size([])
r0.dtype: torch.float32
r0: 1.0
----------------------------------------------
----------------------------------------------
r1.size(): torch.Size([5])
r1.dtype: torch.float32
r1: tensor([1., 2., 3., 4., 5.])
----------------------------------------------
----------------------------------------------
r2.size(): torch.Size([2, 3])
r2.dtype: torch.float32
r2: tensor([[ 1.,  2.,  3.],
        [11., 12., 13.]])
----------------------------------------------
----------------------------------------------
r3.size(): torch.Size([2, 2, 3])
r3.dtype: torch.float32
r3: tensor([[[  1.,   2.,   3.],
         [ 11.,  12.,  13.]],

        [[101., 102., 103.],
         [111., 112., 113.]]])
----------------------------------------------
----------------------------------------------
r3_to2.size(): torch.Size([3, 4])
r3_to2.dtype: torch.float32
r3_to2: tensor([[  1.,   2.,   3.,  11.],
        [ 12.,  13., 101., 102.],
       

In [50]:
print(f"requires_grad: {r1.requires_grad}")
print(f"device: {r1.device}")

item = r0.item()
print(type(item))
print(item)

t1 = torch.ones(1)
print(t1.shape)
print(t1.item())
print(t1)

t2 = torch.ones(1, 1)
print(t2.shape)
print(t2.item())
print(t2)

t3 = torch.ones(1, 1, 1)
print(t3.shape)
print(t3.item())
print(t3)


requires_grad: False
device: cpu
<class 'float'>
1.0
torch.Size([1])
1.0
tensor([1.])
torch.Size([1, 1])
1.0
tensor([[1.]])
torch.Size([1, 1, 1])
1.0
tensor([[[1.]]])


In [56]:
print(r2)
print(r2.max())
print(torch.max(r2, 0))
print(torch.max(r2, 1))
print(torch.max(r2, 1)[1])


tensor([[ 1.,  2.,  3.],
        [11., 12., 13.]])
tensor(13.)
torch.return_types.max(
values=tensor([11., 12., 13.]),
indices=tensor([1, 1, 1]))
torch.return_types.max(
values=tensor([ 3., 13.]),
indices=tensor([2, 2]))
tensor([2, 2])
