<a href="https://colab.research.google.com/github/ueki5/colaboratory/blob/main/playground-017.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install plotly | tail -n 1
!pip install japanize-matplotlib | tail -n 1

In [8]:
import matplotlib.pyplot as plt
import japanize_matplotlib
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
import numpy as np
import pandas as pd

###################################################################
# データ準備
###################################################################
from sklearn.datasets import load_iris

# データ読み込み
iris = load_iris()

# 入力データと正解データ取得
x_org, y_org = iris.data, iris.target

# 結果確認
print('元データ', x_org.shape, y_org.shape)
# print('x_org:', x_org)
# print('y_org:', y_org)

# データ絞り込み
#  クラス0(0-50),1(50-100),2(100-150)
#  項目 sepal_lengthとsepal_widthのみ
x_data = iris.data[:150, :2]
y_data = iris.target[:150]

# 訓練データ、検証データに分割（シャッフルも同時に実施）
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    x_data, y_data, train_size=70, test_size=30,
    random_state=123
)

###################################################################
# グラフ描画（配列使用）
###################################################################
x_t0 = x_train[y_train == 0]
x_t1 = x_train[y_train == 1]
x_t2 = x_train[y_train == 2]
# 散布図（setosa）
data1 = go.Scatter(x=x_t0[:,0], y=x_t0[:,1],
                    mode='markers',
                    name='0(setosa)')
# 散布図（versicolor）
data2 = go.Scatter(x=x_t1[:,0], y=x_t1[:,1],
                    mode='markers',
                    name='1(versicolor)')
# 散布図（virginica）
data3 = go.Scatter(x=x_t2[:,0], y=x_t2[:,1],
                    mode='markers',
                    name='2(virginica)')
fig = go.Figure()
fig.add_trace(data1)
fig.add_trace(data2)
fig.add_trace(data3)

fig.update_xaxes(title="sepal_length",
                 color='grey',
                 ticks='inside',
                 ticklen=5,
                 tickwidth=2,
                 tickcolor='lightgrey'
                 ) # X軸タイトルを指定
fig.update_yaxes(title="sepal_width") # Y軸タイトルを指定
fig.update_layout(title="散布図（訓練データ）") # グラフタイトルを設定
fig.update_layout(showlegend=True) # 凡例を強制的に表示（デフォルトでは複数系列あると表示）
fig.show()

# ###################################################################
# # グラフ描画（DataFrame使用）
# ###################################################################
# df = px.data.iris()
# # 散布図（setosa）
# df_setosa = df.query('species=="setosa"')
# data1 = go.Scatter(x=df_setosa['sepal_width'], y=df_setosa['sepal_length'],
#                     mode='markers',
#                     name='0(setosa)')
# # 散布図（versicolor）
# df_versicolor = df.query('species=="versicolor"')
# data2 = go.Scatter(x=df_versicolor['sepal_width'], y=df_versicolor['sepal_length'],
#                     mode='markers',
#                     name='1(versicolor)')
# df_virginica = df.query('species=="virginica"')
# # 散布図（virginica）
# data3 = go.Scatter(x=df_virginica['sepal_width'], y=df_virginica['sepal_length'],
#                     mode='markers',
#                     name='2(virginica)')
# fig = go.Figure()
# fig.add_trace(data1)
# fig.add_trace(data2)
# fig.add_trace(data3)
# # X軸タイトルを指定
# fig.update_xaxes(title="sepal_length",
#                  color='grey',
#                  ticks='inside',
#                  ticklen=5,
#                  tickwidth=2,
#                  tickcolor='lightgrey'
#                  )
# fig.update_yaxes(title="sepal_width") # Y軸タイトルを指定
# fig.update_layout(title="散布図（訓練データ）") # グラフタイトルを設定
# fig.update_layout(showlegend=True) # 凡例を強制的に表示（デフォルトでは複数系列あると表示）
# fig.show()

# # データの生成
# x = np.outer(np.linspace(2, 4.5, 30), np.ones(30))
# y = x.copy().T
# z = 0.3 * x + -0.7 * y + 0.6
# # 3D曲面プロットの作成
# fig = go.Figure(data=[go.Surface(z=z, x=x, y=y)])
# fig.update_layout(
#     title='3D Surface Plot',
#     autosize=False,
#     width=1200,
#     height=800,
#     margin=dict(l=65, r=50, b=65, t=90))
# fig.show()




元データ (150, 4) (150,)
x_org: [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6