<a href="https://colab.research.google.com/github/ueki5/colaboratory/blob/main/playground-011.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [48]:
!pip install torchviz
!pip install japanize-matplotlib


In [80]:
import numpy as np
import matplotlib.pyplot as plt
import japanize_matplotlib
import torch
from torchviz import make_dot

torch.manual_seed(123)
l1 = torch.nn.Linear(1, 1) # 入力:1, 出力:1
l2 = torch.nn.Linear(2, 1) # 入力:2, 出力:1
l3 = torch.nn.Linear(2, 3) # 入力:2, 出力:3

# 初期値設定
# y = 2*x + 1
torch.nn.init.constant_(l1.weight, 2.0)
torch.nn.init.constant_(l1.bias, 1.0)
# y2 = 1*x1 + 1*x2 + 100
torch.nn.init.constant_(l2.weight[:, 0], 1.0)
torch.nn.init.constant_(l2.weight[:, 1], 3.0)
torch.nn.init.constant_(l2.bias, 100.0)
# y3 = 1*x1 + 3*x2 + 5*x3 + 1000
torch.nn.init.constant_(l3.weight[0, 0], 1.0)
torch.nn.init.constant_(l3.weight[0, 1], 3.0)
torch.nn.init.constant_(l3.weight[1, 0], 5.0)
torch.nn.init.constant_(l3.weight[1, 1], 7.0)
torch.nn.init.constant_(l3.weight[2, 0], 11.0)
torch.nn.init.constant_(l3.weight[2, 1], 13.0)
torch.nn.init.constant_(l3.bias, 1000.0)

# 結果確認
print('-- L1 -------------------------------------------------------------')
print(l1)
for param in l1.named_parameters():
  print(f'name: {param[0]}, tensor: {param[1]}, shape: {param[1].shape}')
print('-- L2 -------------------------------------------------------------')
print(l2)
for param in l2.named_parameters():
  print(f'name: {param[0]}, tensor: {param[1]}, shape: {param[1].shape}')
print('-- L3 -------------------------------------------------------------')
print(l3)
for param in l3.named_parameters():
  print(f'name: {param[0]}, tensor: {param[1]}, shape: {param[1].shape}')

# テスト用データ生成

# 1次元の入力を定義
x_np = np.arange(-2, 2.1, 1)
x = torch.tensor(x_np).float()
# 汎用化のため、2次元テンソルに変換
x = x.view(-1, 1)

print('-- x:1次元のINPUT -------------------------------------------------------------')
print(x.shape)
print(x)

print('-- y = 2x + 1 -------------------------------------------------------------')
y = l1(x)
print(y.shape)
print(y.data)

print('-- x:2次元のINPUT -------------------------------------------------------------')
# 2次元の入力を定義
x2_np = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
x2 = torch.tensor(x2_np).float()
print(x2.shape)
print(x2)

print('-- y2 = x1+3x2 + 100) -------------------------------------------------------------')
y2 = l2(x2)
print(y2.shape)
print(y2.data)

print('-- y3 = [x1+3x2, 5x1+7x2, 11x1+13x2] + 1000) -------------------------------------------------------------')
# 入力は2次元のものを使用
y3 = l3(x2)
print(y3.shape)
print(y3.data)



-- L1 -------------------------------------------------------------
Linear(in_features=1, out_features=1, bias=True)
name: weight, tensor: Parameter containing:
tensor([[2.]], requires_grad=True), shape: torch.Size([1, 1])
name: bias, tensor: Parameter containing:
tensor([1.], requires_grad=True), shape: torch.Size([1])
-- L2 -------------------------------------------------------------
Linear(in_features=2, out_features=1, bias=True)
name: weight, tensor: Parameter containing:
tensor([[1., 3.]], requires_grad=True), shape: torch.Size([1, 2])
name: bias, tensor: Parameter containing:
tensor([100.], requires_grad=True), shape: torch.Size([1])
-- L3 -------------------------------------------------------------
Linear(in_features=2, out_features=3, bias=True)
name: weight, tensor: Parameter containing:
tensor([[ 1.,  3.],
        [ 5.,  7.],
        [11., 13.]], requires_grad=True), shape: torch.Size([3, 2])
name: bias, tensor: Parameter containing:
tensor([1000., 1000., 1000.], requires_