<a href="https://colab.research.google.com/github/ueki5/colaboratory/blob/main/playground-011.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
!pip install torchviz
!pip install japanize-matplotlib


Linear(in_features=1, out_features=1, bias=True)
Linear(in_features=1, out_features=2, bias=True)
Linear(in_features=2, out_features=3, bias=True)
name: weight
tensor: Parameter containing:
tensor([[-0.4078]], requires_grad=True)
shape: torch.Size([1, 1])
name: bias
tensor: Parameter containing:
tensor([0.0331], requires_grad=True)
shape: torch.Size([1])


In [43]:
import numpy as np
import matplotlib.pyplot as plt
import japanize_matplotlib
import torch
from torchviz import make_dot

torch.manual_seed(123)
l1 = torch.nn.Linear(1, 1) # 入力:1, 出力:1
l2 = torch.nn.Linear(2, 1) # 入力:2, 出力:1
l3 = torch.nn.Linear(2, 3) # 入力:2, 出力:3

# print('-- L1 -------------------------------------------------------------')
# print(l1)
# for param in l1.named_parameters():
#   print(f'name: {param[0]}, tensor: {param[1]}, shape: {param[1].shape}')
# print('-- L2 -------------------------------------------------------------')
# print(l2)
# for param in l2.named_parameters():
#   print(f'name: {param[0]}, tensor: {param[1]}, shape: {param[1].shape}')
# print('-- L3 -------------------------------------------------------------')
# print(l3)
# for param in l3.named_parameters():
#   print(f'name: {param[0]}, tensor: {param[1]}, shape: {param[1].shape}')

# 初期値設定
torch.nn.init.constant_(l1.weight, 2.0)
torch.nn.init.constant_(l1.bias, 1.0)
torch.nn.init.constant_(l2.weight, 1.0)
torch.nn.init.constant_(l2.bias, 2.0)
torch.nn.init.constant_(l3.weight[0,:], 1.0)
torch.nn.init.constant_(l3.weight[1,:], 2.0)
torch.nn.init.constant_(l3.weight[2,:], 3.0)
torch.nn.init.constant_(l3.bias, 2.0)

# 結果確認
print('-- l1 -------------------------------------------------------------')
print(f'weight={l1.weight}, bias={l1.bias}')
print('-- l2 -------------------------------------------------------------')
print(f'weight={l2.weight}, bias={l2.bias}')
print('-- l3 -------------------------------------------------------------')
print(f'weight={l3.weight}, bias={l3.bias}')

# テスト用データ生成

print('-- x_npをNumPy配列で定義 -------------------------------------------------------------')
x_np = np.arange(-2, 2.1, 1)
x = torch.tensor(x_np).float()
x = x.view(-1, 1)
print(x.shape)
print(x)

print('-- 一次関数のテスト -------------------------------------------------------------')
y = l1(x)

print(y.shape)
print(y.data)

#
print('-- 2次元NumPy配列 -------------------------------------------------------------')
x2_np = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
x2 = torch.tensor(x2_np).float()
print(x2.shape)
print(x2)

print('-- 一次関数のテスト -------------------------------------------------------------')
y2 = l2(x2)

print(y2.shape)
print(y2.data)



-- L1 -------------------------------------------------------------
Linear(in_features=1, out_features=1, bias=True)
name: weight, tensor: Parameter containing:
tensor([[-0.4078]], requires_grad=True), shape: torch.Size([1, 1])
name: bias, tensor: Parameter containing:
tensor([0.0331], requires_grad=True), shape: torch.Size([1])
-- L2 -------------------------------------------------------------
Linear(in_features=2, out_features=1, bias=True)
name: weight, tensor: Parameter containing:
tensor([[-0.3512,  0.2667]], requires_grad=True), shape: torch.Size([1, 2])
name: bias, tensor: Parameter containing:
tensor([-0.6025], requires_grad=True), shape: torch.Size([1])
-- L3 -------------------------------------------------------------
Linear(in_features=2, out_features=3, bias=True)
name: weight, tensor: Parameter containing:
tensor([[ 0.5183, -0.5140],
        [-0.5622, -0.4468],
        [ 0.3202, -0.2613]], requires_grad=True), shape: torch.Size([3, 2])
name: bias, tensor: Parameter conta